runtime: python311
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app

instance_class: F1

env_variables:
  # --- General Settings ---
  STORAGE_BACKEND: "pg"
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"

  # --- Security ---
  # IMPORTANT: Replace with the URL of your deployed frontend
  CORS_ORIGINS: "http://localhost:5173,https://rau-frontend-dot-test-proj-beltrangs.ue.r.appspot.com"
  # IMPORTANT: Generate a new, strong secret key for production
  SECRET_KEY: "change-this-in-prod"

  # --- Database Connection ---
  # This uses the Neon database URL you provided, adapted for SQLAlchemy's asyncpg driver.
  DATABASE_URL: "postgresql+asyncpg://neondb_owner:npg_kXdMPw4ou8ia@ep-blue-tree-ahuzle4e-pooler.c-3.us-east-1.aws.neon.tech/rau?sslmode=require"
